/**
 * Brand icons for model providers. It maps provider ids onto the bundled mask assets and falls back to a
 * letter badge for providers without one.
 */
import { html, nothing } from "lit";

// Provider identity mapping and mask assets are from the same OpenClaw 2026.9.5 source.
const PROVIDER_ICON_NAMES = new Set([
  "abacus",
  "alibaba",
  "amp",
  "antigravity",
  "arcee",
  "augment",
  "baseten",
  "bedrock",
  "byteplus",
  "cerebras",
  "chutes",
  "claude",
  "clawrouter",
  "cloudflare",
  "codebuff",
  "codex",
  "cohere",
  "comfy",
  "commandcode",
  "copilot",
  "crof",
  "crossmodel",
  "cursor",
  "deepgram",
  "deepinfra",
  "deepseek",
  "devin",
  "doubao",
  "elevenlabs",
  "factory",
  "fal",
  "featherless",
  "fireworks",
  "gemini",
  "grok",
  "groq",
  "huggingface",
  "jetbrains",
  "kilo",
  "kimi",
  "kiro",
  "litellm",
  "llamacpp",
  "llmproxy",
  "lmstudio",
  "longcat",
  "manus",
  "meta",
  "microsoft",
  "mimo",
  "minimax",
  "mistral",
  "novita",
  "nvidia",
  "ollama",
  "opencode",
  "opencodego",
  "openrouter",
  "perplexity",
  "pi",
  "pixverse",
  "poe",
  "qianfan",
  "qoder",
  "runway",
  "sakana",
  "stepfun",
  "synthetic",
  "t3chat",
  "tencent",
  "together",
  "venice",
  "vercel",
  "vertexai",
  "vllm",
  "volcengine",
  "warp",
  "windsurf",
  "zai",
  "zed",
]);
const PROVIDER_ICON_ALIASES: Readonly<Record<string, string>> = {
  anthropic: "claude",
  "amazon-bedrock": "bedrock",
  "aws-bedrock": "bedrock",
  "claude-cli": "claude",
  "cloudflare-ai-gateway": "cloudflare",
  "copilot-proxy": "copilot",
  google: "gemini",
  "google-gemini-cli": "gemini",
  "github-copilot": "copilot",
  kilocode: "kilo",
  "kimi-coding": "kimi",
  "llama-cpp": "llamacpp",
  "microsoft-foundry": "microsoft",
  "minimax-portal": "minimax",
  "ollama-cloud": "ollama",
  // CodexBar names its bundled OpenAI knot asset "codex".
  openai: "codex",
  moonshot: "kimi",
  "opencode-go": "opencodego",
  "opencode-zen": "opencode",
  qwen: "alibaba",
  "qwen-token-plan": "alibaba",
  "stepfun-plan": "stepfun",
  "tencent-tokenhub": "tencent",
  "tencent-tokenplan": "tencent",
  xai: "grok",
  // Xiaomi ships its AI models under the MiMo brand mark.
  xiaomi: "mimo",
  "xiaomi-token-plan": "mimo",
  "vercel-ai-gateway": "vercel",
  "vertex-ai": "vertexai",
  "z-ai": "zai",
  "openai-codex": "codex",
};

export function renderProviderBrandIcon(provider: string, className: string, fallback = true) {
  const name = PROVIDER_ICON_ALIASES[provider] ?? provider;
  return PROVIDER_ICON_NAMES.has(name)
    ? html`<span class=${`provider-brand-icon ${className}`} data-provider-icon=${name} style=${`--provider-icon-url: url("/provider-icons/ProviderIcon-${name}.svg")`} aria-hidden="true"></span>`
    : fallback ? html`<span class=${`provider-brand-icon provider-brand-icon--fallback ${className}`} aria-hidden="true">${provider.slice(0, 1).toUpperCase()}</span>` : nothing;
}
